name: Feature Request

description: Suggest an idea for this project

title: "[Feature Request]"

labels: enhancement

assignees: ''

body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: |
        Please describe the overview of the issue.
      validations:
        required: true