name: Publish

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 'v1.x'
    - run: deno test --allow-all --coverage=cov/
    - run: deno coverage --lcov cov/ > cov.lcov
    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./cov.lcov
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.    
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
  tag:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
         export TAG_NAME=$(cat deno.json | grep "\"version\"" | awk -F'"' '{print $(NF-1)}')
         if [! "$(git tag -l ${TAG_NAME})" ]; then
          echo "Creating tag: ${TAG_NAME}"
          git tag "${TAG_NAME}"
          git push origin "${TAG_NAME}"
         else
            echo "Tag '${TAG_NAME}' already exists."
         fi